export interface TemplateVars {
  issue_title: string;
  issue_number: string;
  issue_url: string;
  issue_body: string;
  issue_labels: string;
  issue_checklist: string;
  detected_domains: string;
  matched_rule_ids: string;
  matched_rule_descriptions: string;
  matched_guardrails: string;
  matched_hints: string;
  prompt_always_files: string;
  prompt_issue_docs: string;
  prompt_issue_sources: string;
  prompt_discovered_docs: string;
  prompt_rule_docs: string;
  prompt_discovered_sources: string;
  prompt_implementation_constraints: string;
  always_docs: string;
  issue_docs: string;
  issue_sources: string;
  discovered_docs: string;
  rule_docs: string;
  missing_docs: string;
  discovered_sources: string;
  repo_path: string;
  generated_at: string;
}
