import test from 'node:test';
import assert from 'node:assert/strict';
import { renderTemplate } from '../../dist/template/renderer.js';

test('renderTemplate replaces normal placeholders', () => {
  assert.equal(
    renderTemplate('Issue {{number}}: {{title}}\n{{body}}', {
      number: '71',
      title: 'Focused tests',
      body: 'Add deterministic coverage.',
    }),
    'Issue 71: Focused tests\nAdd deterministic coverage.'
  );
});

test('renderTemplate throws a clear error for unreplaced brace placeholders', () => {
  assert.throws(
    () => renderTemplate('Hello {{name}} from {{ repo }}', { name: 'Codex' }),
    /Template rendering issue: unreplaced placeholder\(s\): \{\{repo\}\}/
  );
});

test('renderTemplate throws a clear error for uppercase placeholders', () => {
  assert.throws(
    () => renderTemplate('Generated by __AGENT_NAME__', {}),
    /Template rendering issue: unreplaced placeholder\(s\): __AGENT_NAME__/
  );
});

test('renderTemplate ignores non-placeholder syntax that appears in prompts or examples', () => {
  assert.equal(
    renderTemplate('JSON: { enabled: true }\nShell: ${HOME}\nPath: __tests__', {}),
    'JSON: { enabled: true }\nShell: ${HOME}\nPath: __tests__'
  );
});

test('renderTemplate reports unreplaced placeholders in deterministic sorted order', () => {
  assert.throws(
    () => renderTemplate('{{zeta}}\n__TOKEN__\n{{ alpha }}', {}),
    (err) => {
      assert.ok(err instanceof Error);
      assert.equal(
        err.message,
        'Template rendering issue: unreplaced placeholder(s): __TOKEN__, {{alpha}}, {{zeta}}'
      );
      return true;
    }
  );
});
